---
- name: overlay - Fetch kernel package
  get_url: url={{ item.url }} dest=/tmp/ sha256sum={{ item.checksum }}
  with_items: docker_filesystem_overlay_debs

- name: overlay - Install kernel package
  apt: deb=/tmp/{{ item.url | basename }} state=installed
  with_items: docker_filesystem_overlay_debs

- name: overlay - Reboot for new kernel
  command: shutdown -r now 'Ansible - Reboot for new kernel.'

- name: overlay - Wait for reboot
  local_action:
    module: wait_for
      host={{ ansible_ssh_host }}
      port={{ ansible_ssh_port | default(22) }}
      delay=30
      timeout=600
      state=started
  become: no

